from abc import ABC, abstractmethod
from collections.abc import AsyncGenerator

import google.generativeai as genai
import openai

from app.core.config import settings
from app.core.exceptions import AIError
from app.core.logging import logger


class BaseLLMProvider(ABC):
    """
    Abstract interface for swappable LLM model providers.
    Supports standard and streaming text synthesis.
    """

    @abstractmethod
    async def generate_response(
        self, messages: list[dict], system_prompt: str | None = None
    ) -> str:
        """
        Generates a non-streaming text response.
        """
        pass

    @abstractmethod
    async def stream_response(
        self, messages: list[dict], system_prompt: str | None = None
    ) -> AsyncGenerator[str, None]:
        """
        Yields text chunks as they are generated by the model.
        """
        # Yield is inside concrete implementations
        pass


class OpenAILLMProvider(BaseLLMProvider):
    """OpenAI implementation using the official async client."""

    def __init__(self) -> None:
        self.model = getattr(settings, "OPENAI_MODEL", "gpt-4o-mini")
        self.client = openai.AsyncOpenAI(api_key=settings.OPENAI_API_KEY)

    async def generate_response(
        self, messages: list[dict], system_prompt: str | None = None
    ) -> str:
        if not settings.OPENAI_API_KEY:
            raise AIError(message="OPENAI_API_KEY is not configured.")

        formatted_messages = []
        if system_prompt:
            formatted_messages.append({"role": "system", "content": system_prompt})
        formatted_messages.extend(messages)

        try:
            response = await self.client.chat.completions.create(
                model=self.model,
                messages=formatted_messages,
                temperature=0.2,  # Low temperature is critical for accurate RAG synthesis
            )
            return response.choices[0].message.content or ""
        except Exception as e:
            logger.error(f"OpenAI completion failed: {e}")
            raise AIError(message="OpenAI completion call failed") from e

    async def stream_response(
        self, messages: list[dict], system_prompt: str | None = None
    ) -> AsyncGenerator[str, None]:
        if not settings.OPENAI_API_KEY:
            raise AIError(message="OPENAI_API_KEY is not configured.")

        formatted_messages = []
        if system_prompt:
            formatted_messages.append({"role": "system", "content": system_prompt})
        formatted_messages.extend(messages)

        try:
            response = await self.client.chat.completions.create(
                model=self.model,
                messages=formatted_messages,
                temperature=0.2,
                stream=True,
            )
            async for chunk in response:
                if chunk.choices and chunk.choices[0].delta.content:
                    yield chunk.choices[0].delta.content
        except Exception as e:
            logger.error(f"OpenAI streaming completion failed: {e}")
            raise AIError(message="OpenAI streaming completion failed") from e


class GeminiLLMProvider(BaseLLMProvider):
    """Gemini implementation using the async google-generativeai SDK."""

    def __init__(self) -> None:
        self.model_name = "gemini-1.5-pro"
        genai.configure(api_key=settings.GEMINI_API_KEY)

    def _convert_messages(self, messages: list[dict]) -> list[dict]:
        """Maps standard message structures to Gemini contents schema (user -> model)."""
        gemini_contents = []
        for msg in messages:
            role = msg["role"]
            if role == "assistant":
                role = "model"
            # Filter out systems messages from contents (managed by system_instruction)
            if role == "system":
                continue

            gemini_contents.append(
                {
                    "role": role,
                    "parts": [msg["content"]],
                }
            )
        return gemini_contents

    async def generate_response(
        self, messages: list[dict], system_prompt: str | None = None
    ) -> str:
        if not settings.GEMINI_API_KEY:
            raise AIError(message="GEMINI_API_KEY is not configured.")

        contents = self._convert_messages(messages)
        try:
            model = genai.GenerativeModel(
                model_name=self.model_name,
                system_instruction=system_prompt,
            )
            response = await model.generate_content_async(
                contents=contents,
                generation_config=genai.types.GenerationConfig(temperature=0.2),
            )
            return response.text
        except Exception as e:
            logger.error(f"Gemini completion failed: {e}")
            raise AIError(message="Gemini completion call failed") from e

    async def stream_response(
        self, messages: list[dict], system_prompt: str | None = None
    ) -> AsyncGenerator[str, None]:
        if not settings.GEMINI_API_KEY:
            raise AIError(message="GEMINI_API_KEY is not configured.")

        contents = self._convert_messages(messages)
        try:
            model = genai.GenerativeModel(
                model_name=self.model_name,
                system_instruction=system_prompt,
            )
            response = await model.generate_content_async(
                contents=contents,
                generation_config=genai.types.GenerationConfig(temperature=0.2),
                stream=True,
            )
            async for chunk in response:
                if chunk.text:
                    yield chunk.text
        except Exception as e:
            logger.error(f"Gemini streaming completion failed: {e}")
            raise AIError(message="Gemini streaming completion failed") from e


def get_llm_provider() -> BaseLLMProvider:
    """
    Factory function returning the configured LLM provider.
    """
    provider = settings.DEFAULT_LLM_PROVIDER.lower()
    if provider == "openai":
        return OpenAILLMProvider()
    elif provider == "gemini":
        return GeminiLLMProvider()
    else:
        logger.warning(
            f"Unsupported LLM provider: {settings.DEFAULT_LLM_PROVIDER}. Falling back to OpenAI."
        )
        return OpenAILLMProvider()


# Shared system-wide LLM generator client
llm_provider = get_llm_provider()
